"""Public website copy. Order: Japanese, English, Korean, Simplified, Traditional."""
LANGUAGES = [('ja','日本語'),('en','English'),('ko','한국어'),('zh-Hans','简体中文'),('zh-Hant','繁體中文')]
COPY = {
 'title': ['金継 KINTSUGI — 割れた先に、美しさがある。','金継 KINTSUGI — A beautiful way to begin again.','金継 KINTSUGI — 깨어진 자리에서 피어나는 아름다움.','金継 KINTSUGI — 破碎之后，别有新生。','金継 KINTSUGI — 破碎之後，別有新生。'],
 'description': ['指一本で器を継ぎ、工房を育てる。金継ぎを題材にしたiPhoneゲーム、金継 KINTSUGI。現在開発中。','Mend pottery with a fingertip, build your workshop, and meet the spirits within. 金継 KINTSUGI is an iPhone game in development.','손끝으로 도자기를 잇고 공방을 가꾸세요. 킨츠기를 소재로 한 iPhone 게임, 金継 KINTSUGI. 현재 개발 중입니다.','指尖描金，修补器物，经营自己的工房。金継 KINTSUGI，一款以金缮为灵感的 iPhone 游戏，正在开发中。','指尖描金，修補器物，經營自己的工房。金継 KINTSUGI，一款以金繕為靈感的 iPhone 遊戲，正在開發中。'],
 'skip': ['本文へ','Skip to content','본문으로','跳至正文','跳至正文'],
 'nav_game':['遊び方','The craft','플레이','玩法','玩法'],
 'nav_world':['物語','The world','이야기','故事','故事'],
 'nav_release':['リリース情報','Coming soon','출시 소식','发布信息','發佈資訊'],
 'language':['言語','Language','언어','语言','語言'],
 'menu':['メニュー','Menu','메뉴','菜单','選單'],
 'eyebrow':['指先で継ぐ、小さな物語。','A little craft. A little wonder.','손끝으로 잇는 작은 이야기.','指尖描金，续写器物的故事。','指尖描金，續寫器物的故事。'],
 'hero1':['割れた先に、','Every break.','깨어진 자리,','破碎之后，','破碎之後，'],
 'hero2':['美しさがある。','A new beginning.','새로운 아름다움.','别有新生。','別有新生。'],
 'hero_body':['ひとすじの金で、もう一度。\n器を継ぎ、物語に出会う、あなたの小さな工房。','Follow a seam of gold. Bring a vessel back to life.\nFind a little wonder in the work of your own hands.','한 줄기 금빛으로 다시 한번.\n그릇을 잇고 이야기를 만나는, 당신만의 작은 공방.','以一缕金，续一段缘。\n修补器物，邂逅故事，走进属于你的小小工房。','以一縷金，續一段緣。\n修補器物，邂逅故事，走進屬於你的小小工房。'],
 'explore':['工房をのぞく','Step inside','공방 둘러보기','走进工房','走進工房'],
 'coming':['iPhone 向けに開発中','In development for iPhone','iPhone용으로 개발 중','iPhone 版开发中','iPhone 版開發中'],
 'scroll':['金継の世界へ','Discover Kintsugi','킨츠기의 세계로','探索金継的世界','探索金継的世界'],
 'intro_label':['01 / 継ぐということ','01 / THE ART OF MENDING','01 / 잇는다는 것','01 / 修补的艺术','01 / 修補的藝術'],
 'intro_title':['傷あとを、\nその器だけの美しさに。','Something broken.\nSomething one of a kind.','깨진 흔적을,\n오직 그 그릇만의 아름다움으로.','让每一道裂痕，\n成为独一无二的风景。','讓每一道裂痕，\n成為獨一無二的風景。'],
 'intro_body':['割れた器を、漆と金で継ぐ「金継ぎ」。その営みを、指先の遊びにしました。ひびをなぞり、金粉をまき、磨き上げる。一器ずつ、あなたの手の跡が残ります。','Kintsugi mends broken pottery with lacquer and gold. Here, that craft becomes play: trace a fracture, dust it with gold, and polish it to a shine. Every vessel carries the mark of your hand.','옻과 금으로 깨진 도자기를 잇는 킨츠기. 그 손길을 놀이로 담았습니다. 균열을 따라 그리고, 금가루를 뿌리고, 윤을 내세요. 그릇마다 당신의 손길이 남습니다.','金缮以漆和金修补破碎的器物。我们把这份手艺化作指尖的游戏：沿裂痕描线、撒上金粉、细细打磨。每一件器物，都留下你的痕迹。','金繕以漆和金修補破碎的器物。我們把這份手藝化作指尖的遊戲：沿裂痕描線、撒上金粉、細細打磨。每一件器物，都留下你的痕跡。'],
 'play_label':['02 / あなたの工房','02 / YOUR LITTLE WORKSHOP','02 / 당신의 작은 공방','02 / 你的工房','02 / 你的工房'],
 'play_title':['ひと筆から、\n広がっていく。','One golden line.\nA world to make your own.','한 번의 붓질에서\n펼쳐지는 세계.','从一笔金线，\n到一方天地。','從一筆金線，\n到一方天地。'],
 'mend':['継ぐ','Mend','잇기','修补','修補'],
 'collect':['集める','Collect','수집','收藏','收藏'],
 'grow':['育てる','Grow','가꾸기','经营','經營'],
 'mend_title':['指一本で、金をつなぐ。','A fingertip becomes a brush.','손끝이 붓이 됩니다.','指尖轻触，金线相连。','指尖輕觸，金線相連。'],
 'mend_body':['光の拍子に合わせて、ひびをなぞる。修繕で腕を磨いたり、時間を気にせず稽古したり。ひと筆の気持ちよさを、何度でも。','Trace the cracks in time with the light. Test your touch in a challenge, or settle into untimed practice. A simple gesture, a satisfying little transformation.','빛의 박자에 맞춰 균열을 따라가세요. 도전 모드로 실력을 시험하거나 시간 제한 없이 연습할 수 있습니다. 작은 손짓으로 느끼는 변화의 즐거움.','跟随光点的节奏，沿着裂痕描金。在挑战中磨练手艺，或在不限时的练习中慢慢体会。简单的一笔，也能带来修复的满足。','跟隨光點的節奏，沿著裂痕描金。在挑戰中磨練手藝，或在不限時的練習中慢慢體會。簡單的一筆，也能帶來修復的滿足。'],
 'collect_title':['一器ずつ、あなたの蔵へ。','A collection with a history.','한 그릇씩, 당신의 소장품으로.','一件一件，藏进时光。','一件一件，藏進時光。'],
 'collect_body':['楽、志野、織部、有田、九谷、そして唐物。さまざまな器を継いで蔵に収め、銘をつける。手をかけた一器を、じっくり眺めて。','Discover Raku, Shino, Oribe, Arita, Kutani and imported wares. Mend them, give them a name, and make room on your shelf for the pieces you love.','라쿠, 시노, 오리베, 아리타, 구타니, 그리고 당물. 다양한 그릇을 수리하고 이름을 붙여 소장하세요. 정성을 들인 한 점을 천천히 감상해 보세요.','乐烧、志野、织部、有田、九谷，还有唐物。修补不同的器形与釉色，为它们题名，让喜爱的器物在收藏中安家。','樂燒、志野、織部、有田、九谷，還有唐物。修補不同的器形與釉色，為它們題名，讓喜愛的器物在收藏中安家。'],
 'grow_title':['工房の先に、町がある。','Your workshop is only the beginning.','공방 너머에는 마을이 있습니다.','工房之外，小镇渐暖。','工房之外，小鎮漸暖。'],
 'grow_body':['注文を受け、器を鑑定し、茶会へ出かける。仕事を重ねれば、町にも少しずつ灯りが戻る。道具や仲間との出会いが、次の一器へつながります。','Take commissions, visit the appraiser, and prepare for a tea gathering. As your craft grows, help rebuild the town and meet the people who call it home.','주문을 받고 감정을 의뢰하고 다회에 참여하세요. 솜씨가 자랄수록 마을에도 조금씩 온기가 돌아옵니다. 도구와 동료와의 만남이 다음 그릇으로 이어집니다.','接下委托，鉴赏器物，筹备茶会。随着手艺精进，帮助小镇重建，与住在这里的人们相识，让下一件作品有了新的期待。','接下委託，鑑賞器物，籌備茶會。隨著手藝精進，幫助小鎮重建，與住在這裡的人們相識，讓下一件作品有了新的期待。'],
 'screens_note':['開発中の実際のゲーム画面です。内容は変更になる場合があります。','Actual development screenshots. Content may change before release.','개발 중인 실제 게임 화면입니다. 출시 전 내용이 변경될 수 있습니다.','画面来自开发中的实际游戏，内容可能在发布前调整。','畫面來自開發中的實際遊戲，內容可能在發佈前調整。'],
 'world_label':['03 / 器に宿るもの','03 / SPIRITS IN THE CERAMIC','03 / 그릇에 깃든 존재','03 / 器物有灵','03 / 器物有靈'],
 'world_title':['長く愛されたものには、\n心が宿る。','Some things hold\nmore than memories.','오래 사랑받은 물건에는\n마음이 깃듭니다.','被长久珍爱的器物，\n也会拥有自己的心。','被長久珍愛的器物，\n也會擁有自己的心。'],
 'world_body':['器から目覚める、個性豊かな付喪神たち。案内役の「継」をはじめ、それぞれの物語、それぞれの得意技。あなたの工房に、頼もしい仲間が増えていきます。','Meet the tsukumogami: spirits that awaken in cherished objects. With Tsugi as your guide, discover their stories and talents, and welcome a little more life into your workshop.','소중한 물건에서 깨어난 정령, 쓰쿠모가미를 만나세요. 안내역 츠기와 함께 저마다의 이야기와 재능을 알아가며 공방의 동료를 늘려 보세요.','与从器物中苏醒的付丧神相遇。在向导「继」的陪伴下，了解他们的故事与专长，让工房里多一些温暖的伙伴。','與從器物中甦醒的付喪神相遇。在嚮導「繼」的陪伴下，了解他們的故事與專長，讓工房裡多一些溫暖的夥伴。'],
 'tsugi':['継 — 工房の案内役','TSUGI — YOUR GUIDE','츠기 — 공방의 안내역','继 — 工房向导','繼 — 工房嚮導'],
 'spirit_note':['器を継ぐ。縁も、つながる。','Mend a vessel. Find a kindred spirit.','그릇을 잇고, 인연을 만나다.','修补的是器物，结下的是缘分。','修補的是器物，結下的是緣分。'],
 'usurai':['薄氷','Usurai','우스라이','薄冰','薄冰'],
 'hido':['火道','Hidō','히도','火道','火道'],
 'botan':['牡丹姫','Botanhime','보탄히메','牡丹姬','牡丹姬'],
 'release_label':['次の一器は、あなたの手で。','THE NEXT CHAPTER IS IN YOUR HANDS.','다음 그릇은, 당신의 손으로.','下一件器物，等你执笔。','下一件器物，等你執筆。'],
 'release_title':['もうすぐ、\nあなたの手に。','A little patience.\nA little gold.','곧,\n당신의 손안에.','静候一场，\n指尖的相逢。','靜候一場，\n指尖的相逢。'],
 'release_body':['金継 KINTSUGI は現在開発中です。App Store ではまだ配信していません。配信日とダウンロード先は、決まり次第このページでお知らせします。','金継 KINTSUGI is in development and is not yet available on the App Store. We’ll share the release date and download link here when they’re ready.','金継 KINTSUGI는 개발 중이며 아직 App Store에 출시되지 않았습니다. 출시일과 다운로드 링크가 확정되면 이 페이지에서 안내하겠습니다.','金継 KINTSUGI 正在开发中，尚未在 App Store 上架。发布日期和下载链接确定后，我们会在这里公布。','金継 KINTSUGI 正在開發中，尚未在 App Store 上架。發佈日期與下載連結確定後，我們會在這裡公布。'],
 'status':['開発中 · 配信日未定','IN DEVELOPMENT · RELEASE DATE TO COME','개발 중 · 출시일 미정','开发中 · 发布日期待定','開發中 · 發佈日期待定'],
 'support':['サポート','Support','지원','支持','支援'],
 'privacy':['プライバシー','Privacy','개인정보','隐私','隱私'],
 'studio':['Sunimori のアプリ','More from Sunimori','Sunimori의 앱','更多 Sunimori 应用','更多 Sunimori 應用'],
 'footer_note':['ひとつひとつ、心をこめて。','Made with care, one detail at a time.','하나하나, 마음을 담아.','每一处细节，都用心相待。','每一處細節，都用心相待。'],
 'back':['ホームへ戻る','Back to the workshop','홈으로','返回首页','返回首頁'],
 'support_title':['お手伝いできることは、\nありますか。','A helping hand.','무엇을 도와드릴까요?','有什么可以帮你？','有什麼可以幫你？'],
 'support_intro':['ゲームについてのご質問や不具合のご報告は、Sunimori までご連絡ください。','For questions about the game or to report a problem, get in touch with Sunimori.','게임 문의나 문제 신고는 Sunimori로 연락해 주세요.','关于游戏的问题或遇到的故障，欢迎联系 Sunimori。','關於遊戲的問題或遇到的故障，歡迎聯絡 Sunimori。'],
 'faq_release':['どこからダウンロードできますか？','Where can I download it?','어디서 다운로드할 수 있나요?','在哪里可以下载？','在哪裡可以下載？'],
 'faq_device':['対応する端末は？','Which devices is it being made for?','어떤 기기용으로 개발하고 있나요?','支持哪些设备？','支援哪些裝置？'],
 'faq_device_body':['iPhone 向けに開発しています。正式な対応機種と必要な iOS バージョンは、配信時にご案内します。','Kintsugi is being developed for iPhone. Final device compatibility and iOS requirements will be announced at release.','iPhone용으로 개발하고 있습니다. 최종 지원 기기와 iOS 요구 사항은 출시 시 안내합니다.','目前面向 iPhone 开发。最终支持的机型与 iOS 版本要求将在发布时公布。','目前面向 iPhone 開發。最終支援的機型與 iOS 版本要求將在發佈時公布。'],
 'faq_lang':['対応言語は？','Which languages are planned?','어떤 언어를 지원하나요?','计划支持哪些语言？','計劃支援哪些語言？'],
 'faq_lang_body':['現在の開発版は日本語、英語、韓国語、簡体字中国語、繁体字中国語に対応しています。','The current development build supports Japanese, English, Korean, Simplified Chinese and Traditional Chinese.','현재 개발 버전은 일본어, 영어, 한국어, 중국어 간체와 번체를 지원합니다.','目前开发版支持日语、英语、韩语、简体中文和繁体中文。','目前開發版支援日語、英語、韓語、簡體中文和繁體中文。'],
 'contact_title':['お問い合わせ','Contact us','문의하기','联系我们','聯絡我們'],
 'contact_body':['不具合の場合は、端末名、iOS バージョン、アプリのバージョン、起きたことをお知らせください。個人情報やパスワードは送らないでください。','If reporting a problem, include your device model, iOS version, app version and what happened. Please do not send passwords or other sensitive information.','문제 신고 시 기기 모델, iOS 버전, 앱 버전과 발생한 상황을 알려 주세요. 비밀번호나 민감한 정보는 보내지 마세요.','报告问题时，请附上设备型号、iOS 版本、应用版本和问题描述。请勿发送密码或其他敏感信息。','回報問題時，請附上裝置型號、iOS 版本、應用程式版本和問題描述。請勿傳送密碼或其他敏感資訊。'],
 'privacy_title':['プライバシーについて','Privacy, thoughtfully.','개인정보 안내','关于隐私','關於隱私'],
 'updated':['更新日：2026年9月16日','Updated September 16, 2026','업데이트: 2026년 9월 16일','更新于 2026 年 9 月 16 日','更新於 2026 年 9 月 16 日'],
 'privacy_intro':['このページは本ウェブサイトと、現在の開発版について説明します。配信版のデータの取り扱いは、App Store 公開前に確定し、このページを更新します。','This page describes this website and the current development build. We will finalize and update information about the released app’s data practices before its App Store launch.','이 페이지는 웹사이트와 현재 개발 버전을 설명합니다. 정식 앱의 데이터 처리 방침은 App Store 출시 전에 확정하여 업데이트합니다.','本页介绍此网站及当前开发版本的情况。正式版的数据处理说明将在 App Store 上架前确认并更新。','本頁介紹此網站及目前開發版本的情況。正式版的資料處理說明將在 App Store 上架前確認並更新。'],
 'p_site':['このウェブサイト','This website','이 웹사이트','此网站','此網站'],
 'p_site_body':['アクセス解析、広告トラッカー、アカウント登録、入力フォームは使用していません。選んだ言語だけをブラウザ内に保存します。ページの配信には GitHub Pages を利用しており、GitHub がセキュリティなどの目的で IP アドレス等のアクセス情報を記録する場合があります。','We do not use analytics, advertising trackers, accounts or submission forms on this website. Your chosen language is saved locally in your browser. GitHub Pages hosts these pages; GitHub may record request information, including IP addresses, for security and operational purposes.','이 웹사이트에는 분석 도구, 광고 추적기, 계정 또는 제출 양식이 없습니다. 선택한 언어만 브라우저에 저장합니다. 호스팅 제공자인 GitHub Pages는 보안 및 운영 목적으로 IP 주소 등의 요청 정보를 기록할 수 있습니다.','本网站不使用流量分析、广告追踪、账号注册或提交表单。选择的语言仅保存在浏览器本地。页面由 GitHub Pages 托管，GitHub 可能出于安全与运营目的记录 IP 地址等访问信息。','本網站不使用流量分析、廣告追蹤、帳號註冊或提交表單。選擇的語言僅儲存在瀏覽器本機。頁面由 GitHub Pages 託管，GitHub 可能基於安全與營運目的記錄 IP 位址等存取資訊。'],
 'p_game':['開発中のゲーム','The game in development','개발 중인 게임','开发中的游戏','開發中的遊戲'],
 'p_game_body':['現在の開発版では、進行状況とプレイ診断を端末に保存します。Game Center を有効にした場合は、スコアが Apple に送信されます。任意のリワード広告機能を開発しているため、配信版に広告が含まれる場合は、広告サービスによるデータの取り扱いを公開前に追記します。','The current development build stores progress and play diagnostics on the device. If Game Center is enabled, scores are sent to Apple. Optional rewarded ads are under development; if advertising is enabled in the released app, this page will explain the ad provider’s data practices before launch.','현재 개발 버전은 진행 상황과 플레이 진단 정보를 기기에 저장합니다. Game Center를 활성화하면 점수가 Apple로 전송됩니다. 선택형 보상 광고를 개발 중이며, 정식 앱에서 광고를 사용하게 되면 출시 전에 광고 제공자의 데이터 처리 내용을 안내합니다.','当前开发版本将进度与游玩诊断保存在设备上。启用 Game Center 后，分数会发送给 Apple。我们正在开发可选的激励广告；如果正式版启用广告，会在上架前补充广告服务商的数据处理说明。','目前開發版本將進度與遊玩診斷儲存在裝置上。啟用 Game Center 後，分數會傳送給 Apple。我們正在開發可選的獎勵廣告；如果正式版啟用廣告，會在上架前補充廣告服務商的資料處理說明。'],
 'p_email':['お問い合わせの情報','When you contact us','문의 시 제공하는 정보','当你联系我们','當你聯絡我們'],
 'p_email_body':['メールでご連絡いただいた場合、返信と問題の調査のためにメールアドレスとお送りいただいた内容を利用します。削除のご依頼も同じ窓口へお送りください。','If you email us, we use your email address and the information you provide to reply and investigate your request. You can use the same address to request deletion of your support correspondence.','이메일로 문의하시면 답변과 문제 조사를 위해 이메일 주소와 제공하신 내용을 사용합니다. 문의 기록 삭제 요청도 같은 주소로 보내실 수 있습니다.','通过邮件联系我们时，我们会使用你的邮箱地址和提供的信息来回复及调查问题。你也可以通过同一邮箱申请删除相关支持邮件。','透過郵件聯絡我們時，我們會使用你的信箱地址和提供的資訊來回覆及調查問題。你也可以透過同一信箱申請刪除相關支援郵件。'],
 'github_privacy':['GitHub のプライバシーステートメント','GitHub Privacy Statement','GitHub 개인정보처리방침','GitHub 隐私声明','GitHub 隱私聲明'],
 'not_found':['このページは見つかりませんでした。','This page could not be found.','페이지를 찾을 수 없습니다.','没有找到此页面。','沒有找到此頁面。']
}

from extra_locales import EXTRA_LANGUAGES, EXTRA
for code, name in EXTRA_LANGUAGES:
    assert EXTRA[code].keys() == COPY.keys(), (code, COPY.keys() - EXTRA[code].keys(), EXTRA[code].keys() - COPY.keys())
    for key in COPY:
        COPY[key].append(EXTRA[code][key])
    LANGUAGES.append((code, name))
